//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDGS81NETEntities : DbContext
    {
        public IDGS81NETEntities()
            : base("name=IDGS81NETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Genero> Genero { get; set; }
        public DbSet<PAGINA> PAGINA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<ROLPAGINA> ROLPAGINA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
