//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public int id_Categoria { get; set; }
        public string nombre_Categoria { get; set; }
        public string kDescripcio { get; set; }
        public Nullable<int> Estatus { get; set; }
    }
}
