//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public string nombreEmpelado { get; set; }
        public string apellidoEmpleado { get; set; }
        public Nullable<int> iDepartamento { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string empleadoCelular { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
