//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGINA
    {
        public PAGINA()
        {
            this.ROLPAGINA = new HashSet<ROLPAGINA>();
        }
    
        public int IDPAGINA { get; set; }
        public string MENSAJE { get; set; }
        public string ACCION { get; set; }
        public string CONTROLADOR { get; set; }
        public Nullable<int> ESTATUS { get; set; }
    
        public virtual ICollection<ROLPAGINA> ROLPAGINA { get; set; }
    }
}
