//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.ROLPAGINA = new HashSet<ROLPAGINA>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IDROL { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ESTATUS { get; set; }
    
        public virtual ICollection<ROLPAGINA> ROLPAGINA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
