//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evidencia1ClaseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLPAGINA
    {
        public int IDROLPAGINA { get; set; }
        public Nullable<int> ROL { get; set; }
        public Nullable<int> PAGINA { get; set; }
        public Nullable<int> ESTATUS { get; set; }
    
        public virtual PAGINA PAGINA1 { get; set; }
        public virtual ROL ROL1 { get; set; }
    }
}
